# Generated by Django 4.2.7 on 2024-01-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0002_rename_name_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
    ]
