# Generated by Django 4.2.7 on 2024-01-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0003_rename_event_id_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
